on: [push]

jobs:
  dispatch_event:
    runs-on: ubuntu-latest
    name: Dispatch event

    steps:
    - uses: juztcode/repo-ditpatch-action@v1
      with:
        event-type: opened
        token: ${{ secrets.PR_UPDATER_TOKEN }}
        repository: AutoModality/action-hello-world-docker
        
