on:
  - push
jobs:
  git-commit:
    runs-on: ubuntu-latest
    name: Testing commit
    steps:
    - name: Commit from bash
      run: |
          echo "Roller was here" > test.txt
    - id: git_commit
      uses: zwaldowski/git-commit-action@v1
    - run: echo "${{ steps.git_commit.outputs.sha }}"
    