on:
  - push
  - pull_request
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: automodality/hello-world-javascript-action@pr-branch
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Looking for PR Branch
      run: echo ${{ github.payload.pull_request.head.ref }}
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"