on:
  - push
jobs:
  realease-race:
    runs-on: [self-hosted, linux, x64, org]
    name: Demonstrates organization wide Self Hosted Runner
    steps:
      - name: Show some environment details
        run: |
          whoami
          cat /etc/hostname
          pwd
