on:
  - push
jobs:
  realease-race:
    runs-on: [ ubuntu-16.04, ubuntu-16.04 ]
    name: Demonstrates only one host will release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
