on:
  - push
jobs:
  realease-race:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04,windows-2019 ]
    name: Demonstrates only one host will release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify of Release
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PR_UPDATER_TOKEN }}
          repository: AutoModality/action-hello-world-docker
          event-type: release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "package":"ros-melodic-example", "new_release_version": "${{ steps.semantic.outputs.new_release_version }}", "new_release_notes": "${{ steps.semantic.outputs.new_release_notes }}", "new_release_major_version": "${{ steps.semantic.outputs.new_release_major_version }}", "new_release_minor_version":"${{ steps.semantic.outputs.new_release_minor_version }}","new_release_patch_version":"${{ steps.semantic.outputs.new_release_patch_version }}"}'
