on: issue_comment

jobs:
  dispatch_event:
    runs-on: ubuntu-latest
    name: Dispatch event

    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PR_UPDATER_TOKEN }}
        repository: AutoModality/action-hello-world-docker
        event-type: release
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "package":"ros-melodic-example", "new_release_version": "1.2.3", "new_release_notes": "Dispatching release notes AM-246", "new_release_major_version": "major", "new_release_minor_version":"minor","new_release_patch_version":"patch"}'
